Implemented art feature
Real-Dev-Squad/website-www pull request #143
Opened 2021-08-09 18:29 UTC by PayalHake1402

2021-08-11 05:33 UTC, PayalHake1402 commented
I have created a pull request with updated changes . Please review it.

2021-08-14 12:03 UTC, harshith-venkatesh requested changes

2021-08-14 12:03 UTC, harshith-venkatesh commented on art-feature-august-2021.html
> +      function run() {
please follow indentation as the code is not properly indented

2021-08-14 12:03 UTC, harshith-venkatesh commented on art-feature-august-2021.html
> +        .addEventListener("keyup", run);
can we have more meaningful function name please

2021-08-14 12:03 UTC, harshith-venkatesh commented on css/main.css
> +  flex-direction: row;
flex direction is row by default, we can remove this

2021-08-19 15:50 UTC, harshith-venkatesh commented on art-feature-august-2021.html
> +        .addEventListener("keyup", run);
Probably, like sanitizedCodeOutput , sanitizedHtml
Just few suggestions, looks more descriptive too right

2021-12-27 19:27 UTC, rohan09-raj commented
There were no further developments That's why this has been already taken care of and merged with PR #155

2021-12-27 19:27 UTC, closed without merging