Fix Scroll top Button
Real-Dev-Squad/website-www pull request #227
Opened 2022-01-23 14:00 UTC by 7ORP3DO

### Issue : 

Fix Issue: #221 

### Is Development Tested?

- [x] Yes
- [ ] No

### Before / After Change Screenshots

Before :

https://user-images.githubusercontent.com/80192140/150681942-c89ecabc-515a-4a9c-b52c-e3e5b5f0293c.mp4

After :

https://user-images.githubusercontent.com/80192140/150681972-03e92721-9ed7-4936-a44d-0d5adf03921d.mp4

2022-01-24 12:28 UTC, rohan09-raj requested changes

2022-01-24 12:28 UTC, rohan09-raj commented on js/scrollBtn.js
> +function scrollFunction() {
Can we please use es6 functions ??

2022-01-24 12:28 UTC, rohan09-raj commented on css/main.css
> +  /* bottom: 20px; */
Can we please remove this dead code ??

2022-01-24 12:31 UTC, 7ORP3DO commented on css/main.css
> +  /* bottom: 20px; */
Sure 👍

2022-01-25 04:05 UTC, rohan09-raj approved these changes
Thanks for the changes, good work, approving your PR 🎉 
Congrats on getting your first PR merged to Real Dev Squad

2022-01-25 04:08 UTC, merged