#305 Moving constants to a common repo.
Real-Dev-Squad/website-www pull request #340
Opened 2022-12-08 20:18 UTC by JAYATEJA04

### Moving important constants to a common repo.

### What is the change?

- Made an npm package to store all the important constant variables in the join.js file. Importing variables is done by installing the npm package. To install the package, run `npm i www-constants` in the terminal. After installing the package, the variables are imported by using the "require" keyword. The package which store the variables is named "www-constants".
- All the constants which are commented on are the ones which have been stored in the npm package.

2022-12-16 02:16 UTC, rohan09-raj commented on package.json
> +    "www-constants": "^1.0.2"
Where this dependency is located?

2022-12-16 02:18 UTC, rohan09-raj commented on js/join.js
> +// };
Why the code is being commented here?

2022-12-16 02:18 UTC, rohan09-raj commented on js/join.js
> +//
Why the code is being commented here?

2022-12-16 02:18 UTC, rohan09-raj commented on js/join.js
> +//
Why the code is being commented here?

2022-12-16 02:18 UTC, rohan09-raj commented on js/join.js
> +//
Why the code is being commented here?

2022-12-16 02:18 UTC, rohan09-raj commented on js/join.js
> +//
Why the code is being commented here?

2022-12-16 11:13 UTC, RitikJaiswal75 requested changes
Why is my join.js file being changed it will break the join section. As per the requirements we were looking for an npm package that can have all the constants and we can use them everywhere.

2022-12-16 11:15 UTC, RitikJaiswal75 commented
Please do not use a feature that is already created, create a new POC and hide it behind a feature flag

2023-03-25 17:23 UTC, rohan09-raj commented
Closing this PR as this has been continued in a separate new repository 
https://github.com/JAYATEJA04/realdevsquad-constants
Message Reference: https://discord.com/channels/673083527624916993/1007355818603192360/1069837282095419413

2023-03-25 17:23 UTC, closed without merging