[Ember-Migration] [Tests] Scroll to Top
Real-Dev-Squad/website-www pull request #394
Opened 2023-01-22 06:37 UTC by ranitasahaa1230

### Issue

##### Example : Closes #<issue_number>

### What is the change?

Provide a small description in points of what did you change

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

Before :
Image/Video

After :
Image/Video

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

2023-01-22 12:09 UTC, rohan09-raj requested changes

2023-01-22 12:09 UTC, rohan09-raj commented on tests/integration/components/scroll-to-top-test.js
> +    await click('[data-test-scroll-to-top]');
Can we please test for the action that is being performed at the click of this button?
This means when the button is clicked, the page scrolls to position 0 (check the `scroll-to-top.js` for reference)
that is needed to be tested here.

2023-01-22 12:09 UTC, rohan09-raj commented on tests/integration/components/scroll-to-top-test.js
> +
Please check why the GitHub actions are failing

2023-02-07 12:34 UTC, rohan09-raj commented on tests/integration/components/scroll-to-top-test.js
> +    await click('[data-test-scroll-to-top]');
You can test the components in the following steps :
- Scroll the window a little bit using `scrollTo`
- Click the `scroll-to-top` button 
- Write an assert  to check the height that it is `0` or not.

2023-02-14 13:14 UTC, satyam73 commented on tests/integration/components/scroll-to-top-test.js
> +    await scrollTo('#scroll__btn', 0, 100);
Use data-test selector here too.

2023-03-25 13:54 UTC, rohan09-raj commented
PR became stale and the author is not working on it anymore. Closing the PR and reassigning the issue

2023-03-25 13:54 UTC, closed without merging