Feat/404 page
Real-Dev-Squad/website-www pull request #396
Opened 2023-01-26 10:08 UTC by shubhamsigdar1

### Issue

Closes #395

### What is the change?
Step1: yarn install which install all dependencies for a project

Step2: In terminal i write "ember generate route page-not-found" which create 3 file inside folder
          1. app\routes\page-not-found.js
          2. app\templates\page-not-found.hbs
          3. tests\unit\routes\page-not-found-test.js  
          
Step3: I make changes in the route.js file, then make changes in  app\templates\page-not-found.hbs file
          then create  file in styles folder (styles/page-not-found.css) and add styling in  page-not-found.css

Step4: In terminal i write "npm run lint:fix"

### Is Development Tested?

-  Yes

### Before / After Change Screenshots

![404-page](https://user-images.githubusercontent.com/107163260/214754833-3f5261e8-c127-4abe-ac14-0ea8be420539.gif)

2023-01-27 19:02 UTC, satyam73 requested changes
I think you can change the classes according to BEM convention

2023-01-27 19:06 UTC, satyam73 requested changes

2023-01-27 19:06 UTC, satyam73 commented on app/styles/page-not-found.css
> +  .page-not-found-img {
```We can change class names according to BEM convention
  .page-not-found__img {

```

2023-01-27 19:06 UTC, satyam73 commented on app/styles/page-not-found.css
> +  .page-not-found-text{
```similarly here
  .page-not-found__text{

```

2023-01-27 19:06 UTC, satyam73 commented on app/templates/page-not-found.hbs
> +	<img class="page-not-found-img" src="../assets/images/not-found.png" alt="not-found">
```suggestion
	<img class="page-not-found__img" src="../assets/images/not-found.png" alt="not-found">
```

2023-01-27 19:06 UTC, satyam73 commented on app/templates/page-not-found.hbs
> +	<h1 class="page-not-found-text">The page you're looking for cannot be found!</h1>
```suggestion
	<h1 class="page-not-found__text">The page you're looking for cannot be found!</h1>
```

2023-01-30 10:22 UTC, rohan09-raj requested changes

2023-01-30 10:22 UTC, rohan09-raj commented on app/styles/page-not-found.css
> +  }
Can we please fix the formatting here?
Apologies for not configuring the pre-commit hook. I will do it, then linting issues can be prevented

2023-01-30 10:22 UTC, rohan09-raj commented on app/styles/page-not-found.css
> +    font-size: 15px;
We can remove the font-size and font-weight properties from here and instead use the `h4 tag` whose font size is 16px and font-weight: bolder.

2023-01-30 10:22 UTC, rohan09-raj commented on tests/unit/routes/page-not-found-test.js
> +      .dom('.page-not-found .page-not-found__img')
Try using `data-test-selectors` for picking up the DOM elements

2023-01-30 10:22 UTC, rohan09-raj commented on tests/unit/routes/page-not-found-test.js
> +      .dom('.page-not-found .page-not-found__text')
Try using `data-test-selectors` for picking up the DOM elements

2023-01-30 10:22 UTC, rohan09-raj commented on tests/unit/routes/page-not-found-test.js
> +  test('visiting /*', async function (assert) {
Can we please have a line space here?

2023-01-30 10:22 UTC, rohan09-raj commented on app/templates/page-not-found.hbs
> +</div>
Can we please fill the page with the remaining space, means on the `scroll: 0` there should be only navbar and 404 content visible, then after scrolling a bit, footer should appear. Refer to the link and screenshot below.

**Link :** https://realdevsquads.vercel.app/join
![Screenshot from 2023-01-30 15-42-44](https://user-images.githubusercontent.com/78433013/215449836-653ad41e-b122-46c3-a5f3-e777746086da.png)
![image](https://user-images.githubusercontent.com/78433013/215449954-22029070-c159-48f5-bb51-f344e3acd654.png)
![image](https://user-images.githubusercontent.com/78433013/215449729-cb823566-f9df-436e-b71f-b1357b36a5d7.png)

2023-01-30 10:22 UTC, rohan09-raj commented on app/styles/page-not-found.css
> +    width: 20%;
We can maybe use `px` because in the video demonstration, I can see the image becoming too small.
Add media query for mobile view if necessary

2023-01-31 01:33 UTC, shubhamsigdar1 commented
![scroll 0](https://user-images.githubusercontent.com/107163260/215636420-57c4bb61-746b-440f-84a8-4be8e9c8a74a.gif)

2023-01-31 09:18 UTC, rohan09-raj approved these changes
Great work in here 💯. I hope you enjoyed learning EmberJS

2023-01-31 09:19 UTC, merged