[Feat #491]: Add 100ms sdk to join room
Real-Dev-Squad/website-www pull request #493
Opened 2023-06-03 06:56 UTC by SanketDhabarde

### Join the 100ms room

##### Closes #491 

### What is the change?
We integrated 100ms to join the live session. The API which is used to get the token or join the room will be replaced with the backed APIs when they are ready.

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots
https://github.com/Real-Dev-Squad/website-www/assets/40385118/c40f3d7a-6711-402e-b843-fb0d9b91c955

2023-06-04 10:05 UTC, satyam73 requested changes

2023-06-04 11:31 UTC, SanketDhabarde commented on app/controllers/live.js
>        this.name = '';
That's generally what we do right when we set up any form. So if the user having some error they don't have to clear the name manually and type again.

2023-06-04 11:34 UTC, SanketDhabarde commented on app/controllers/live.js
> +  @tracked role = null;
This role will be taken from queryParams. So if we don't add the queryParams it's basically null. From that idea, I have kept it null. An empty string is still some value.

2023-06-04 13:39 UTC, satyam73 commented on app/controllers/live.js
>        this.name = '';
got it

2023-06-04 13:40 UTC, satyam73 approved these changes
LGTM

2023-06-11 10:50 UTC, satyam73 approved these changes
LGTM👍✨
Good work @SanketDhabarde

2023-06-11 10:50 UTC, satyam73 commented on app/controllers/live.js
> +  @globalRef('videoEl') videoEl;
NIT : remove this unused declaration

2023-06-11 17:54 UTC, rohan09-raj approved these changes
Great work @SanketDhabarde 💯 💯 Merging your PR

2023-06-11 17:54 UTC, merged