fix/redirection if not logged in store the lastlocation and redirect …
Real-Dev-Squad/website-www pull request #497
Opened 2023-06-17 12:12 UTC by Abhay5855

### Issue

##### When we are at /intro?id= page and if not logged in we get redirected to login and then home, https://github.com/Real-Dev-Squad/website-www/issues/486

### What is the change?
If the user is not logged in and tries to access the intro/:id page, we are redirecting it to the Login page and after successful login, it is redirecting it back to the previous page i.e. intro/:id page instead of the home page.

- In the intro.js we checked if the user is not logged in showing an alert message to redirect him back to the Login page.
- When he tries to access the intro/:id page without login, we are storing the location in session storage so as to access the previous location when logged in.
- On the home page if a user is logged in and if the previous location is present I am redirecting it back to the location which I have stored in the session storage and also removing it as well from storage.

### Is Development Tested?

[ ] Yes
[ x ] No

### Before / After Change Screenshots

Before :

https://github.com/Real-Dev-Squad/website-www/assets/71277980/dae1630b-7df7-489a-a060-01c72aafef3f

After :

https://github.com/Real-Dev-Squad/website-www/assets/71277980/6a6ca3ba-7c6e-4d12-a089-58a510e044fd

2023-06-17 12:23 UTC, Pratiyushkumar requested changes

2023-06-17 12:23 UTC, Pratiyushkumar commented on js/user.js
> +  });
use constant for api url

2023-06-17 12:23 UTC, Pratiyushkumar commented on js/user.js
> +  });
use makeApiCall  function already written in  util.js

2023-06-18 14:28 UTC, Pratiyushkumar commented on index.html
>    </body>
why not put this script above all the files, try to prioritize the scripts

2023-06-19 12:12 UTC, Pratiyushkumar approved these changes
LGTM

2023-06-19 12:13 UTC, Pratiyushkumar reviewed
take one more approvals from any member as well

2023-06-19 12:29 UTC, shubhamsigdar1 commented on js/intro.js
> +      sessionStorage.setItem('lastLocation', window.location.href);
Nit: lastLocationUrl

2023-06-19 12:37 UTC, shubhamsigdar1 commented on js/user.js
> +    setUserGreeting(result.username, result.first_name, result.picture?.url); // BAD
why you are repeating setUserGreeting fn two times

2023-06-19 15:34 UTC, Pratiyushkumar submitted a review, later dismissed
LGTM

2023-06-19 17:40 UTC, Abhay5855 commented
@shubhamsigdar1 I have done the changes please review once

2023-06-20 13:44 UTC, shubhamsigdar1 submitted a review, later dismissed

2023-06-22 09:25 UTC, shubhamsigdar1 approved these changes

2023-06-22 09:46 UTC, sahsisunny approved these changes
LGTM

2023-06-22 16:35 UTC, Pratiyushkumar submitted a review, later dismissed
LGTM

2023-06-22 20:57 UTC, shubhamsigdar1 approved these changes

2023-06-23 20:28 UTC, prakashchoudhary07 commented
Can we directly pass the redirect URL in AUTH URL it self for redirection

2023-06-24 17:08 UTC, harshith-venkatesh commented on js/user.js
> +    setUserGreeting(result.username, result.first_name, result.picture?.url); // BAD
What do you mean by BAD

2023-06-24 17:46 UTC, harshith-venkatesh approved these changes

2023-06-24 21:35 UTC, sahsisunny approved these changes

2023-06-28 05:04 UTC, Abhay5855 commented
> Can we directly pass the redirect URL in AUTH URL itself for redirection

Hey @prakashchoudhary07 , This might need to add a additional function which does the same thing again and check again if the user is logged in again, which is already done in the user function.

2023-06-30 18:09 UTC, merged