[Live Site] Minor improvements in live
Real-Dev-Squad/website-www pull request #504
Opened 2023-06-25 12:40 UTC by SanketDhabarde

### Add some improvements to the live site

##### Closes #500 

### What is the change?
- Added loader
- Button to copy the invite link
- Controls to panel

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots

https://github.com/Real-Dev-Squad/website-www/assets/40385118/e550b3a3-e587-459d-b3dc-f413ccf8d02c

2023-06-25 17:16 UTC, vvaibhavdesai approved these changes

2023-06-27 05:16 UTC, satyam73 approved these changes

2023-06-27 06:38 UTC, rohan09-raj requested changes

2023-06-27 06:38 UTC, rohan09-raj commented on app/components/live-sidebar.hbs
> +        <img data-test-sidebar-host-image class='host__image' src={{if @hostProfilePicture @hostProfilePicture 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png' }
Can we please use this image to make it consistent on all sites https://github.com/Real-Dev-Squad/website-www/blob/develop/img/profile.png

2023-06-27 06:38 UTC, rohan09-raj commented on app/controllers/live.js
> +      case 'leave-room':
Can we please make use of enums (constants) here?

2023-06-27 06:38 UTC, rohan09-raj commented on app/templates/live.hbs
> -            <VideoScreen @src='/assets/birds_footage.mp4' />
Can we please remove this resource from the assets ?
Also there is one host.svg that is also not utilized I guess, can we please remove that as well ?

2023-06-27 11:45 UTC, rohan09-raj approved these changes

2023-06-27 11:46 UTC, merged