changed designs for dropdown
Real-Dev-Squad/website-www pull request #529
Opened 2023-07-17 21:41 UTC by fakhruddinkw

This is regarding : https://github.com/Real-Dev-Squad/todo-action-items/issues/151

**OLD**
![old-drop-down-www](https://github.com/Real-Dev-Squad/website-www/assets/85249044/a455302f-f1e6-409e-8d44-a5d9a1a091d2)

**NEW**
![new-drop-down-www](https://github.com/Real-Dev-Squad/website-www/assets/85249044/1d18dfaa-fff6-48df-9bb9-cc2ef57a587f)

2023-07-29 09:07 UTC, sahsisunny commented on css/navbar.css
Could you please create the variables for the color and convert the unit of measurement to REM if the value is less than 10PX?

2023-07-29 09:08 UTC, sahsisunny commented
Where is the test?

2023-07-30 07:08 UTC, shubhamsigdar1 commented on css/navbar.css
+

2023-07-30 07:10 UTC, shubhamsigdar1 reviewed
great work @fakhruddinkw 
just worked on @sahsisunny comment
ping me I will approved

I just seen my-site, Is there is any arrow
<img width="166" alt="image" src="https://github.com/Real-Dev-Squad/website-www/assets/107163260/f4d00e65-025c-48e2-9823-ae1e1e1d9ee3">

please make video also

2023-08-01 09:49 UTC, fakhruddinkw commented
> great work @fakhruddinkw just worked on @sahsisunny comment ping me I will approved
> 
> I just seen my-site, Is there is any arrow in your changes?? <img alt="image" width="166" src="https://user-images.githubusercontent.com/107163260/257037579-f4d00e65-025c-48e2-9823-ae1e1e1d9ee3.png">
> 
> please make one video please and show how toggle of arrow is working

to add arrow, i ll have to add Font awesome as dependency in package.json, i have asked for approval, if its approved i ll add arrow @shubhamsigdar1

2023-08-02 13:08 UTC, sahsisunny requested changes
We have several HTML pages that require the same dropdown menu. Please create this dropdown using JavaScript and add it to each page.

2023-08-03 09:48 UTC, sahsisunny approved these changes

2023-08-03 15:27 UTC, shubhamsigdar1 approved these changes

2023-08-04 07:58 UTC, merged