Updated background image and font style
Real-Dev-Squad/website-www pull request #56
Opened 2020-10-02 09:16 UTC by Mohit049

2020-10-10 03:23 UTC, ankushdharkar requested changes
@Mohit049 Thanks for the PR. Some small changes are needed before we can approve and merge this. Thanks

2020-10-10 03:23 UTC, ankushdharkar commented on index.html
> +      <h1 class="welcome-title" style=" font-size:50px;font-family:algerian,verdana; color:navy;"> Welcome to Real Dev Squad </h1>
Let's move this into the main css file please

2020-10-10 03:23 UTC, ankushdharkar commented on index.html
> +<body style="background-image:url(https://theartmad.com/wp-content/uploads/2015/09/Best-Light-Website-Backgrounds-5.jpg);>
Let's keep the css in it's css files please. No inline styling is preferrable

2021-01-09 18:52 UTC, swarajpure commented
@Mohit049 are you going to make the changes?

2021-01-24 20:46 UTC, closed without merging