fix to run on local enviroment
Real-Dev-Squad/website-www pull request #616
Opened 2023-08-31 15:44 UTC by Pratiyushkumar

2023-08-31 16:34 UTC, shubhamsigdar1 approved these changes

2023-08-31 17:46 UTC, iamitprakash submitted a review, later dismissed

2023-09-01 06:28 UTC, satyam73 reviewed
Why the prod one got changes to localhost:3000?

2023-09-01 06:30 UTC, Pratiyushkumar commented
> Why the prod one got changes to localhost:3000?

![image](https://github.com/Real-Dev-Squad/website-www/assets/82165483/af8f75f0-3273-4357-8b5e-04cd2b81b184)
it's inside development not prod

2023-09-04 12:15 UTC, shubhamsigdar1 submitted a review, later dismissed

2023-09-04 15:46 UTC, satyam73 requested changes

2023-09-04 15:46 UTC, satyam73 commented on app/constants/urls.js
> +const DEVELOPMENT = 'localhost:3000';
DEVELOPMENT_DOMAIN will be better

2023-09-06 06:50 UTC, satyam73 approved these changes
LGTM

2023-09-06 10:55 UTC, shubhamsigdar1 approved these changes

2023-09-06 13:46 UTC, merged