Feature/choose role
Real-Dev-Squad/website-www pull request #646
Opened 2023-09-15 06:17 UTC by shubhamsigdar1

### Issue

##### Example : Closes #<issue_number>

### What is the change?

Provide a small description in points of what did you change

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

Before :
Image/Video

After :
Image/Video

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

2023-09-16 23:00 UTC, iamitprakash commented on app/components/stepper-signup.js
> +    if (key === 'role') {
can't be use Enum over here

2023-09-16 23:12 UTC, iamitprakash requested changes
Implementation looks pretty complex to me, can we talk on this

2023-09-17 00:31 UTC, shubhamsigdar1 commented
> Implementation looks pretty complex to me, can we talk on this

yes

2023-09-17 09:35 UTC, iamitprakash approved these changes

2023-09-17 09:35 UTC, merged