[Live-Site] Add warning modal before event end
Real-Dev-Squad/website-www pull request #701
Opened 2023-10-12 15:17 UTC by SanketDhabarde

### Add warning modal

##### Closes #685 

### What is the change?
Added warning modal before the host ends the event.

### Is Development Tested?

- [x] Yes
- [ ] No

### Before / After Change Screenshots

https://github.com/Real-Dev-Squad/website-www/assets/40385118/a587f6a9-2b70-455e-8fe5-15e619c5ebc3

https://github.com/Real-Dev-Squad/website-www/assets/40385118/b10c69c1-8f66-4f94-8914-4a17ba1586bf

### Responsiveness
![modal](https://github.com/Real-Dev-Squad/website-www/assets/40385118/eb994d24-8da1-455f-9ce4-728a01b3ed74)

2023-10-12 15:53 UTC, Pratiyushkumar reviewed
can you please write the tests for it and share test coverge

2023-10-12 20:30 UTC, Achintya-Chatterjee reviewed
@SanketDhabarde please add tests stats

2023-10-12 23:08 UTC, satyam73 commented on app/components/kickout-modal.hbs
> +      @onClick={{this.confirmFun}}
confirmFun is not looking good in naming, what about `onConfirmClick` or just `onConfirm`

2023-10-14 08:29 UTC, iamitprakash submitted a review, later dismissed

2023-10-14 17:38 UTC, Pratiyushkumar submitted a review, later dismissed
LGTM

2023-10-15 08:12 UTC, satyam73 requested changes

2023-10-15 08:13 UTC, satyam73 commented
Can you please add mobile version of modal too?
Upto 280px it should work

2023-10-15 15:15 UTC, SanketDhabarde commented on app/components/kickout-modal.hbs
> +      @onClick={{this.confirmFun}}
Now that I think about it. I guess `confirmHandler` will be good. what do you think?

2023-10-15 15:21 UTC, SanketDhabarde commented
> Can you please add mobile version of modal too? Upto 280px it should work

It's the same as kickout modal. No change.

2023-10-15 15:27 UTC, satyam73 commented on app/components/kickout-modal.hbs
> +      @onClick={{this.confirmFun}}
works

2023-10-19 08:33 UTC, satyam73 approved these changes
LGTM

2023-10-22 06:24 UTC, shubhamsigdar1 approved these changes

2023-10-22 06:28 UTC, merged