modeified css for role choose card
Real-Dev-Squad/website-www pull request #716
Opened 2023-10-26 17:30 UTC by skt17

### Issue

##### Example : Closes #<issue_number>

### What is the change?

Provide a small description in points of what did you change

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

Before :
Image/Video

After :
Image/Video

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

2023-10-27 08:04 UTC, satyam73 requested changes

2023-10-27 08:04 UTC, satyam73 commented on app/styles/cards.module.css
> +    align-items: normal;
Why .card has been changed?
If somewhere else this class has been used it will break the UI there as it is general class which I told you I guess

2023-10-27 12:03 UTC, shubhamsigdar1 commented
please Fill the description

2023-10-27 12:17 UTC, iamitprakash requested changes
Proper PR details are missing

2023-11-21 08:31 UTC, satyam73 commented
Closing this PR in respect of this PR https://github.com/Real-Dev-Squad/website-www/pull/748

2023-11-21 08:31 UTC, satyam73 commented
Closing this PR in respect of this PR https://github.com/Real-Dev-Squad/website-www/pull/748

2023-11-21 08:31 UTC, closed without merging