Feat/event logs api
Real-Dev-Squad/website-www pull request #723
Opened 2023-10-31 18:54 UTC by satyam73

### Issue

##### Example : Closes #<issue_number>

### What is the change?

Provide a small description in points of what did you change

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

Before :
Image/Video

After :
Image/Video

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

2023-11-02 08:45 UTC, shubhamsigdar1 commented
Can you please add screenshot or video in description

2023-11-02 08:56 UTC, shubhamsigdar1 commented on app/components/events/logs-page.js
> +  }
What you trying to achieve above from line 30-37

2023-11-03 11:05 UTC, vinit717 requested changes
Please improve PR description and why there are no tests

2023-11-03 17:32 UTC, iamitprakash requested changes
PR details are missing, please add it

2023-11-04 12:37 UTC, shubhamsigdar1 approved these changes

2023-11-04 15:52 UTC, vinit717 approved these changes

2023-11-04 18:48 UTC, iamitprakash approved these changes

2023-11-04 18:49 UTC, merged