[Ember-Migration] Footer Enhancement
Real-Dev-Squad/website-www pull request #724
Opened 2023-11-01 06:27 UTC by ajoykumardas12

### Issue
dynamically render footer depending on route
##### Example : Closes #<issue_number>

### What is the change?

Provide a small description in points of what did you change

##### Example :

- Done this
- Made these changes

### Is Development Tested?

- [ ] Yes
- [ ] No

### Before / After Change Screenshots

For visual or interaction changes. Please provide a video / screenshot.

##### Example:

Before :
Image/Video

After :
Image/Video

**Note :**
What to delete and what not to

- Keep the headings and answer the questions.
- Delete the examples
- Delete the description below headings `What is the change?` & `Before/After Screenshots`

2023-11-02 15:04 UTC, satyam73 requested changes

2023-11-02 15:04 UTC, satyam73 commented on app/components/footer.hbs
any tests for the newly added part?

2023-11-03 12:35 UTC, ajoykumardas12 commented on app/components/footer.hbs
I have added acceptance test for the changes.

2023-11-03 14:12 UTC, ajoykumardas12 commented
### Test stats for newly added tests

![Screenshot_test](https://github.com/Real-Dev-Squad/website-www/assets/87164140/7e60c07b-3c1f-430a-8e82-e67c39463018)

2023-11-04 07:22 UTC, satyam73 approved these changes
LGTM

2023-11-04 09:01 UTC, ardourApeX approved these changes

2023-11-04 11:29 UTC, iamitprakash approved these changes

2023-11-04 12:58 UTC, shubhamsigdar1 approved these changes

2023-11-04 18:30 UTC, merged