How join ember
Real-Dev-Squad/website-www pull request #725
Opened 2023-11-01 10:52 UTC by suryxks

### Issue
##### Example : Closes #717 

### What is the change?

- Made Changes needed for the How to join section migration to ember
- Changes added under feature flag
- Join button disabled
- Tests added for the changes

### Is Development Tested?

- [x] Yes
- [ ] No

Before :
![123](https://github.com/Real-Dev-Squad/website-www/assets/71174744/b7f07b84-d8b8-4557-bcd3-04ad851be195)

After :
[screen-capture (1).webm](https://github.com/Real-Dev-Squad/website-www/assets/71174744/a15d7352-4cd3-45a0-abb0-2f8402113e6c)

![12](https://github.com/Real-Dev-Squad/website-www/assets/71174744/076b9d0a-71b9-461e-b1ad-cae5b4fd42b1)

2023-11-02 14:55 UTC, satyam73 requested changes

2023-11-02 14:55 UTC, satyam73 commented on tests/acceptance/migration-changes-under-feature-flag-test.js
when you're visiting any route first it should be check if you reached that route thereafter any thing should be tested.

2023-11-02 14:56 UTC, satyam73 commented on app/components/join-section.hbs
> +  <h3 data-test-join-title class='join__title join__title_dev'>How Can you Join?</h3>
```suggestion
  <h3 data-test-join-title class='join__title join__title_dev'>How can you Join?</h3>
```

2023-11-02 14:59 UTC, satyam73 commented
Please add a video while resizing it to 280px.

2023-11-02 17:24 UTC, suryxks commented on app/styles/join-section.module.css
> +  font-family: 'Nunito', 'Roboto', sans-serif;
This font was used in the vanilla  site in  production
Link to place where it is used : https://github.com/Real-Dev-Squad/website-www/blob/0ed7020dab3a5ef0eab2f6d53a1c86ae8edc9550/css/main.css#L35

2023-11-02 17:27 UTC, suryxks commented on app/index.html
Added links for the fonts needed Nunito and Roboto

2023-11-02 17:30 UTC, suryxks commented on app/components/join-section.hbs
> +  <h3 data-test-join-title class='join__title join__title_dev'>How Can you Join?</h3>
done

2023-11-02 17:56 UTC, suryxks commented
> Please add a video while resizing it to 280px.

added it in the PR description Please check it

2023-11-02 18:17 UTC, suryxks commented on tests/acceptance/migration-changes-under-feature-flag-test.js
I have checked it with `assert.strictEqual(currentURL(), '/')` and  ` assert.strictEqual(currentURL(), '/?dev=true')`

2023-11-02 18:17 UTC, suryxks commented on app/styles/variables.css
> +  --color-button-dissabled:#a59f9f;
fixed

2023-11-02 18:17 UTC, suryxks commented on app/styles/join-section.module.css
> +  background-color: var(--color-button-dissabled);
fixed

2023-11-02 18:19 UTC, suryxks commented on app/styles/join-section.module.css
changed the classNames according to BEM convention

2023-11-02 18:22 UTC, suryxks commented on app/components/join-section.hbs
> +  <p data-test-para='1' class='join__para join__para_dev'>Our squad focuses on quality and we
fixed

2023-11-04 07:18 UTC, satyam73 commented on app/styles/join-section.module.css
> +.join__later__text{
```suggestion
.join__later-text{
```

2023-11-04 07:18 UTC, satyam73 commented on app/styles/join-section.module.css
> +
NIT: remove this spacing

2023-11-04 07:18 UTC, satyam73 commented on app/styles/join-section.module.css
improve spacing of this file

2023-11-04 07:18 UTC, satyam73 commented on app/components/join-section.hbs
> +  <h3 data-test-join-title class='join__title join__title_dev'>How can you Join?</h3>
```suggestion
  <h3 data-test-join-title class='join__title join__title_dev'>How can you join?</h3>
```

2023-11-04 07:18 UTC, satyam73 commented on tests/acceptance/migration-changes-under-feature-flag-test.js
Can we write for `data-test-join-later-text` this too?

2023-11-04 07:18 UTC, satyam73 commented on app/styles/join-section.module.css
> +  font-family: 'Nunito', 'Roboto', sans-serif;
Yes we're using Raleway as our main font

2023-11-04 11:45 UTC, suryxks commented on app/styles/join-section.module.css
> +  font-family: 'Nunito', 'Roboto', sans-serif;
changed to Raleway

2023-11-04 11:45 UTC, suryxks commented on app/styles/join-section.module.css
> +.join__later__text{
done

2023-11-04 11:45 UTC, suryxks commented on app/styles/join-section.module.css
> +
removed spacing as per suggestion

2023-11-04 11:46 UTC, suryxks commented on app/styles/join-section.module.css
done

2023-11-04 11:46 UTC, suryxks commented on app/components/join-section.hbs
> +  <h3 data-test-join-title class='join__title join__title_dev'>How can you Join?</h3>
done

2023-11-04 11:46 UTC, suryxks commented on tests/acceptance/migration-changes-under-feature-flag-test.js
added test for `data-test-join-later-text`

2023-11-05 07:02 UTC, satyam73 commented on app/index.html
Links removed since we're using Raleway in the app

2023-11-05 07:02 UTC, satyam73 commented on app/styles/join-section.module.css
> +  font-family: 'Nunito', 'Roboto', sans-serif;
Thanks

2023-11-05 07:31 UTC, satyam73 submitted a review, later dismissed
LGTM

2023-11-06 08:20 UTC, ardourApeX commented
This branch has conflicts

2023-11-07 05:11 UTC, satyam73 approved these changes

2023-11-07 05:12 UTC, merged