update:ember changes for main-section done
Real-Dev-Squad/website-www pull request #726
Opened 2023-11-01 16:12 UTC by devananth

### Issue

##### Example : Closes #715

### What is the change?

- Synced beta site with main-section with vanilla site main-section
- Migration changes are under `?dev=true` feature flag

### Is Development Tested?

- [ ] Yes
- [x] No

### Before / After Change Screenshots

Before :
![image](https://github.com/Real-Dev-Squad/website-www/assets/52454081/4a113512-a7ac-4145-b3df-606a63a11db3)

After :
![image](https://github.com/Real-Dev-Squad/website-www/assets/52454081/9f9b7a77-298f-47f3-81c9-a9d74a62604c)

### Video of Changes
https://www.loom.com/share/ab9ecdc31e2b409c8a3dad61bf819fe6?sid=328272c7-51c6-46d8-b84e-ab278e0cc383

**Note :**
- The changes are under ?dev=true feature flag

**Follow Up:**
- The feature flag should be removed from these changes after migration changes are confirmed.

2023-11-02 16:44 UTC, devananth commented on app/styles/header.module.css
> +
removed the space

2023-11-02 16:44 UTC, devananth commented on app/components/header.hbs
changed the classnames according to BEM convention.

2023-11-02 16:45 UTC, devananth commented on app/components/header.hbs
> +<section aria-label='header under dev feature flag' class='header--dev'>
changed `header` to `main`

2023-11-02 16:46 UTC, devananth commented on public/assets/images/hero-community.png
Yes, it is available in `.png` format took this `img` from production site.

2023-11-02 16:46 UTC, devananth commented on tests/acceptance/migration-changes-under-feature-flag-test.js
Added additional tests for all the elements under the `feature flag`

2023-11-02 18:12 UTC, devananth commented on app/styles/header.module.css
> +@media (min-width: 420px){
Changed to breakpoints already used in the app

2023-11-02 18:13 UTC, devananth commented on yarn.lock
Not sure about the changes. But deleted the file and downloaded from repo and pushed changes.

2023-11-04 07:00 UTC, satyam73 commented on app/components/header.hbs
> +        <div class='social__links'>
there's no block named social, please follow BEM convention

2023-11-04 07:01 UTC, satyam73 commented on app/styles/header.module.css
> +  font-size: 1.125em;
Use rem for fonts

2023-11-04 07:01 UTC, satyam73 commented on app/styles/header.module.css
> +
NIT: extra spacin here

2023-11-04 07:04 UTC, satyam73 requested changes

2023-11-04 07:04 UTC, satyam73 commented on app/components/header.hbs
> +        <div class='social__links'>
there's no block named social, please follow BEM convention

2023-11-04 07:04 UTC, satyam73 commented on app/styles/header.module.css
> +  font-size: 1.125em;
use rem for fonts

2023-11-04 07:04 UTC, satyam73 commented on app/styles/header.module.css
use rem units please so that it is consistent throughout the code

2023-11-04 08:06 UTC, devananth commented on app/styles/header.module.css
> +
removed the space.

2023-11-04 08:07 UTC, devananth commented on app/components/header.hbs
> +        <div class='social__links'>
changed, added a `block social`.

2023-11-04 08:07 UTC, devananth commented on app/styles/header.module.css
> +  font-size: 1.125em;
changed to rem.

2023-11-04 08:08 UTC, devananth commented on app/styles/header.module.css
Replaced atmost all `px` to `rem`

2023-11-05 06:52 UTC, satyam73 approved these changes

2023-11-05 09:59 UTC, shubhamsigdar1 approved these changes

2023-11-06 08:12 UTC, merged