Fix Card Width
Real-Dev-Squad/website-www pull request #748
Opened 2023-11-17 07:01 UTC by khemchand-twt11

### Issue

 fixes #697 

### What is the change?
Changed with of `Join the Event` card on small screen

### Is Development Tested?

- [ ] Yes
- [x] No
because there is just UI change

### Before 

![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/ea0f8ff5-163b-4d2c-93c3-b3ea03a11d45)
For visual or interaction changes. Please provide a video / screenshot.

### After

#### Small Screen

![small-screen](https://github.com/Real-Dev-Squad/website-www/assets/84411728/570c1b91-5b5a-45ec-9c3c-6468c09b57ac)

2023-11-17 10:03 UTC, sahsisunny approved these changes

2023-11-18 09:31 UTC, satyam73 requested changes

2023-11-18 09:31 UTC, satyam73 commented on app/styles/cards.module.css
> +    padding: 30px 20px;
do not change the general stylings, this can break the UI of other component which is using this class

2023-11-18 09:33 UTC, satyam73 commented
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/aacccddc-04ae-4e89-a119-f69ed05ea32b)
it says have you tested locally, you should be selecting yes as option.

2023-11-20 11:58 UTC, satyam73 approved these changes
LGTM

2023-11-20 15:02 UTC, shubhamsigdar1 approved these changes

2023-11-20 16:05 UTC, sahsisunny approved these changes

2023-11-21 08:32 UTC, merged