Refactor application status card
Real-Dev-Squad/website-www pull request #833
Opened 2024-01-10 16:58 UTC by vinit717

Date: `10-01-2024`

Developer Name: `vinit`

---

## Issue Ticket Number:-

- add issue ticket number here e.g `#923`

## Description:

Refactor the status card to show icons for different statuses

Is Under Feature Flag

- [ ] Yes
- [ ] No

Database changes

- [ ] Yes
- [ ] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

- [ ] Yes
- [ ] No

Is Development Tested?

- [ ] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [ ] No

### Add relevant Screenshot below ( e.g test coverage etc. )

2024-01-12 08:40 UTC, satyam73 requested changes

2024-01-12 08:40 UTC, satyam73 commented on tests/integration/components/status-card-test.js
More tests can be added for other status as well

2024-01-12 08:41 UTC, satyam73 commented
Can we have rejected icon color to be red?

2024-01-13 06:23 UTC, vinit717 commented
> Can we have rejected icon color to be red?

Can't get it can you elaborate more?

2024-01-13 06:24 UTC, vinit717 commented on tests/integration/components/status-card-test.js
added one more case if more tes t should be added then I'll cover in different PR

2024-01-16 16:39 UTC, satyam73 commented
> > Can we have rejected icon color to be red?
> 
> Can't get it can you elaborate more?

This icon will look good in red imo
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/a5af550e-795f-4fcb-b9f9-b23d0cbfd0b5)

2024-01-16 16:42 UTC, satyam73 requested changes

2024-01-16 16:42 UTC, satyam73 commented on tests/integration/components/status-card-test.js
> +      .doesNotExist("Here's the feedback for your application");
```suggestion
      .doesNotExist();
```

2024-01-16 16:42 UTC, satyam73 commented on tests/integration/components/status-card-test.js
Please create and attach ticket here

2024-01-17 05:34 UTC, vinit717 commented on tests/integration/components/status-card-test.js
https://github.com/Real-Dev-Squad/website-www/issues/839

2024-01-18 17:30 UTC, prakashchoudhary07 approved these changes

2024-01-18 18:13 UTC, satyam73 approved these changes

2024-01-18 18:14 UTC, merged