Feat: prefill first name in input for events
Real-Dev-Squad/website-www pull request #873
Opened 2024-02-15 18:53 UTC by jsuryakt

Date: 16 Feb 2024

Developer Name: Jayasurya

---

## Issue Ticket Number:-

#865 

## Description:

Prefill first name of user in events input field

Is Under Feature Flag

- [x] Yes
- [ ] No

Database changes

- [ ] Yes
- [x] No

Breaking changes (If your feature is breaking/missing something please mention pending tickets)

- [ ] Yes
- [x] No

Is Development Tested?

- [x] Yes
- [ ] No

Tested in staging?

- [ ] Yes
- [x] No

2024-02-17 12:33 UTC, iamitprakash requested changes
test case is missing

2024-02-17 13:07 UTC, jsuryakt commented
> test case is missing

There are test cases with name already set, do you mean e2e test?

2024-02-20 07:11 UTC, ajoykumardas12 commented on tests/integration/components/live-join-test.js
> +      roomCode: '',
This test explicitly sets the name and then checks if name is rendered. Can we instead set login data and check if first name is rendered?

2024-02-20 15:50 UTC, satyam73 commented
The input can be disabled then if name is already filled

2024-02-20 15:53 UTC, jsuryakt commented
> The input can be disabled then if name is already filled

Why? The user can edit it if needed and also if we disable the input, then there is no use of showing it at all, can just proceed with other fields.

2024-02-21 09:54 UTC, ajoykumardas12 commented on tests/integration/components/live-join-test.js
> +      roomCode: '',
Controller name value assertion looks good to me.

2024-02-21 09:59 UTC, ajoykumardas12 commented
> The input can be disabled then if name is already filled

If not logged in and joining as guest, name won't pre-filled. Not sure if it can/should be disabled when logged in.

2024-02-21 10:15 UTC, ajoykumardas12 approved these changes

2024-02-21 18:04 UTC, iamitprakash approved these changes

2024-02-21 18:04 UTC, merged